
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /_ah/admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /reset
  script: index.py
  login: admin

- url: /.*
  script: index.py
